version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"

  api:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
